name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      # You may pin to the exact commit or the version.
      # uses: pypa/gh-action-pypi-publish@717ba43cfbb0387f6ce311b169a825772f54d295
    - name: pypi-publish
      uses: pypa/gh-action-pypi-publish@v1.5.0
      with:
        # Password for your PyPI user or an access token
        password: ${{ secrets.PYPI_API_TOKEN }}
